import {
  INSTALLMENT_STATUS,
  type InstallmentStatus,
  type Locale,
} from "@quitto/shared";

export interface DocText {
  amount: string;
  dueDate: string;
  emptyParty: string;
  generatedAt: (a: { date: string }) => string;
  installmentOfTotal: (a: { n: number; total: number }) => string;
  overdue: (a: { count: number }) => string;
  paidAt: string;
  paidSeal: string;
  payer: string;
  progressSummary: (a: {
    overdue: string;
    paid: string;
    percent: number;
    total: string;
  }) => string;
  quittanceSentence: (a: { date: string; title: string }) => string;
  receiptSentence: (a: {
    amount: string;
    n: number;
    paidAt: string;
    title: string;
    total: number;
  }) => string;
  receiptTitle: string;
  receiver: string;
  statementTitle: string;
  status: Record<InstallmentStatus, string>;
  tableHeaders: readonly [string, string, string, string, string];
}

const DOC_TEXT: Record<Locale, DocText> = {
  "pt-BR": {
    receiptTitle: "RECIBO DE PAGAMENTO",
    statementTitle: "EXTRATO DO CONTRATO",
    paidSeal: "QUITADO",
    payer: "Pagador",
    receiver: "Recebedor",
    amount: "Valor",
    dueDate: "Vencimento",
    paidAt: "Pago em",
    emptyParty: "—",
    installmentOfTotal: ({ n, total }) => `Parcela ${n} de ${total}`,
    receiptSentence: ({ amount, n, total, title, paidAt }) =>
      `Declaramos o recebimento de ${amount} referente à parcela ${n}/${total} do contrato "${title}", paga em ${paidAt}.`,
    quittanceSentence: ({ title, date }) =>
      `Contrato "${title}" quitado por inteiro em ${date}.`,
    generatedAt: ({ date }) => `Documento gerado pelo Quitto em ${date}.`,
    progressSummary: ({ total, paid, percent, overdue }) =>
      `Total ${total} · Pago ${paid} · ${percent}% quitado · ${overdue}`,
    overdue: ({ count }) => (count === 1 ? "1 atrasada" : `${count} atrasadas`),
    tableHeaders: ["Nº", "Vencimento", "Valor", "Status", "Pago em"],
    status: {
      [INSTALLMENT_STATUS.pending]: "Pendente",
      [INSTALLMENT_STATUS.awaitingConfirmation]: "Aguardando confirmação",
      [INSTALLMENT_STATUS.confirmed]: "Confirmada",
      [INSTALLMENT_STATUS.disputed]: "Contestada",
      [INSTALLMENT_STATUS.paid]: "Paga",
    },
  },
  "en-US": {
    receiptTitle: "PAYMENT RECEIPT",
    statementTitle: "CONTRACT STATEMENT",
    paidSeal: "PAID IN FULL",
    payer: "Payer",
    receiver: "Payee",
    amount: "Amount",
    dueDate: "Due date",
    paidAt: "Paid on",
    emptyParty: "—",
    installmentOfTotal: ({ n, total }) => `Installment ${n} of ${total}`,
    receiptSentence: ({ amount, n, total, title, paidAt }) =>
      `We confirm receipt of ${amount} for installment ${n}/${total} of the contract "${title}", paid on ${paidAt}.`,
    quittanceSentence: ({ title, date }) =>
      `Contract "${title}" paid in full on ${date}.`,
    generatedAt: ({ date }) => `Document generated by Quitto on ${date}.`,
    progressSummary: ({ total, paid, percent, overdue }) =>
      `Total ${total} · Paid ${paid} · ${percent}% paid · ${overdue}`,
    overdue: ({ count }) => `${count} overdue`,
    tableHeaders: ["#", "Due date", "Amount", "Status", "Paid on"],
    status: {
      [INSTALLMENT_STATUS.pending]: "Pending",
      [INSTALLMENT_STATUS.awaitingConfirmation]: "Awaiting confirmation",
      [INSTALLMENT_STATUS.confirmed]: "Confirmed",
      [INSTALLMENT_STATUS.disputed]: "Disputed",
      [INSTALLMENT_STATUS.paid]: "Paid",
    },
  },
};

export function docText(locale: Locale): DocText {
  return DOC_TEXT[locale];
}

export function docStatusLabel(
  status: InstallmentStatus,
  locale: Locale
): string {
  return DOC_TEXT[locale].status[status];
}

/** ASCII slug for a safe Content-Disposition filename. */
export function slug(value: string, fallback = "documento"): string {
  return (
    value
      .normalize("NFKD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .toLowerCase()
      .slice(0, 60) || fallback
  );
}

/** recibo-<slug>-parcela-<n>.pdf, extrato-<slug>.csv, or the English twins. */
export function documentFilename(args: {
  ext: "pdf" | "csv";
  kind: "receipt" | "statement";
  locale: Locale;
  sequence?: number;
  title: string;
}): string {
  const en = args.locale === "en-US";
  const name = slug(args.title, en ? "document" : "documento");
  if (args.kind === "statement") {
    return `${en ? "statement" : "extrato"}-${name}.${args.ext}`;
  }
  return en
    ? `receipt-${name}-installment-${args.sequence}.${args.ext}`
    : `recibo-${name}-parcela-${args.sequence}.${args.ext}`;
}

export function exportFilename(locale: Locale): string {
  return locale === "en-US" ? "quitto-my-data.json" : "quitto-meus-dados.json";
}
